### ISSUE TITLE
Mac的下载不了

### ISSUE THREAD

**Issue by 8iiiiiiii** [goldenduo/TestCat#1]

**Comment by goldenduo** [comment]
fixed

**Comment by 8iiiiiiii** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by 8iiiiiiii** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
